// flow-typed signature: abbc35c326e65bf7a7b7dce1864fec9f
// flow-typed version: <<STUB>>/reactstrap_v^8.7.1/flow_v0.14.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactstrap/dist/reactstrap.cjs' {
  declare module.exports: any;
}

declare module 'reactstrap/dist/reactstrap.es' {
  declare module.exports: any;
}

declare module 'reactstrap/dist/reactstrap.full' {
  declare module.exports: any;
}

declare module 'reactstrap/dist/reactstrap.full.min' {
  declare module.exports: any;
}

declare module 'reactstrap/dist/reactstrap' {
  declare module.exports: any;
}

declare module 'reactstrap/dist/reactstrap.min' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Alert' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Badge' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Breadcrumb' {
  declare module.exports: any;
}

declare module 'reactstrap/es/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Button' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ButtonGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ButtonToggle' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Card' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardBody' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardColumns' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardDeck' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardFooter' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardImg' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardImgOverlay' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardLink' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardSubtitle' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardText' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CardTitle' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Carousel' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CarouselCaption' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CarouselControl' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CarouselIndicators' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CarouselItem' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Col' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Collapse' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Container' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CustomFileInput' {
  declare module.exports: any;
}

declare module 'reactstrap/es/CustomInput' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Dropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/es/DropdownContext' {
  declare module.exports: any;
}

declare module 'reactstrap/es/DropdownItem' {
  declare module.exports: any;
}

declare module 'reactstrap/es/DropdownMenu' {
  declare module.exports: any;
}

declare module 'reactstrap/es/DropdownToggle' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Fade' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Form' {
  declare module.exports: any;
}

declare module 'reactstrap/es/FormFeedback' {
  declare module.exports: any;
}

declare module 'reactstrap/es/FormGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/es/FormText' {
  declare module.exports: any;
}

declare module 'reactstrap/es' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Input' {
  declare module.exports: any;
}

declare module 'reactstrap/es/InputGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/es/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'reactstrap/es/InputGroupButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/es/InputGroupText' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Jumbotron' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Label' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ListGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ListGroupItem' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ListGroupItemHeading' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ListGroupItemText' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Media' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Modal' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ModalBody' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ModalFooter' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ModalHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Nav' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Navbar' {
  declare module.exports: any;
}

declare module 'reactstrap/es/NavbarBrand' {
  declare module.exports: any;
}

declare module 'reactstrap/es/NavbarText' {
  declare module.exports: any;
}

declare module 'reactstrap/es/NavbarToggler' {
  declare module.exports: any;
}

declare module 'reactstrap/es/NavItem' {
  declare module.exports: any;
}

declare module 'reactstrap/es/NavLink' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Pagination' {
  declare module.exports: any;
}

declare module 'reactstrap/es/PaginationItem' {
  declare module.exports: any;
}

declare module 'reactstrap/es/PaginationLink' {
  declare module.exports: any;
}

declare module 'reactstrap/es/polyfill' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Popover' {
  declare module.exports: any;
}

declare module 'reactstrap/es/PopoverBody' {
  declare module.exports: any;
}

declare module 'reactstrap/es/PopoverHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/es/PopperContent' {
  declare module.exports: any;
}

declare module 'reactstrap/es/PopperTargetHelper' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Portal' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Progress' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Row' {
  declare module.exports: any;
}

declare module 'reactstrap/es/setupTests' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Spinner' {
  declare module.exports: any;
}

declare module 'reactstrap/es/TabContent' {
  declare module.exports: any;
}

declare module 'reactstrap/es/TabContext' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Table' {
  declare module.exports: any;
}

declare module 'reactstrap/es/TabPane' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Toast' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ToastBody' {
  declare module.exports: any;
}

declare module 'reactstrap/es/ToastHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/es/Tooltip' {
  declare module.exports: any;
}

declare module 'reactstrap/es/TooltipPopoverWrapper' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledAlert' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledCarousel' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledCollapse' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledPopover' {
  declare module.exports: any;
}

declare module 'reactstrap/es/UncontrolledTooltip' {
  declare module.exports: any;
}

declare module 'reactstrap/es/utils' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Alert' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Badge' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Breadcrumb' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Button' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ButtonGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ButtonToggle' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Card' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardBody' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardColumns' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardDeck' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardFooter' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardImg' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardImgOverlay' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardLink' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardSubtitle' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardText' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CardTitle' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Carousel' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CarouselCaption' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CarouselControl' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CarouselIndicators' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CarouselItem' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Col' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Collapse' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Container' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CustomFileInput' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/CustomInput' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Dropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/DropdownContext' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/DropdownItem' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/DropdownMenu' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/DropdownToggle' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Fade' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Form' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/FormFeedback' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/FormGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/FormText' {
  declare module.exports: any;
}

declare module 'reactstrap/lib' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Input' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/InputGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/InputGroupButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/InputGroupText' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Jumbotron' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Label' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ListGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ListGroupItem' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ListGroupItemHeading' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ListGroupItemText' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Media' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Modal' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ModalBody' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ModalFooter' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ModalHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Nav' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Navbar' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/NavbarBrand' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/NavbarText' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/NavbarToggler' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/NavItem' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/NavLink' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Pagination' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/PaginationItem' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/PaginationLink' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/polyfill' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Popover' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/PopoverBody' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/PopoverHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/PopperContent' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/PopperTargetHelper' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Portal' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Progress' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Row' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/setupTests' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Spinner' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/TabContent' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/TabContext' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Table' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/TabPane' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Toast' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ToastBody' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/ToastHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/Tooltip' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/TooltipPopoverWrapper' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledAlert' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledCarousel' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledCollapse' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledPopover' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/UncontrolledTooltip' {
  declare module.exports: any;
}

declare module 'reactstrap/lib/utils' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Alert.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Badge.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Breadcrumb.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/BreadcrumbList.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Button.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ButtonDropdown.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ButtonGroup.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ButtonToggle.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ButtonToolbar.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Card.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardBody.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardColumns.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardDeck.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardFooter.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardGroup.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardHeader.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardImg.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardImgOverlay.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardLink.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardSubtitle.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardText.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CardTitle.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Carousel.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Col.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Collapse.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Container.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/CustomInput.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Dropdown.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/DropdownItem.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/DropdownMenu.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/DropdownToggle.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Fade.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Form.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/FormFeedback.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/FormGroup.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/FormText.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Input.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/InputGroup.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/InputGroupAddon.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/InputGroupButtonDropdown.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/InputGroupText.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Jumbotron.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Label.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ListGroup.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ListGroupItem.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ListGroupItemHeading.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ListGroupItemText.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Media.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Modal.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ModalBody.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ModalFooter.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ModalHeader.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Nav.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Navbar.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/NavbarText.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/NavbarToggler.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/NavBrand.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/NavItem.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/NavLink.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Pagination.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/PaginationItem.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/PaginationLink.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Popover.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/PopoverBody.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/PopoverHeader.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/PopperContent.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Progress.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Row.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Spinner.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Table.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Tabs.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Toast.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ToastBody.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/ToastHeader.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Tooltip.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/TooltipPopoverWrapper.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/Uncontrolled.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/UncontrolledCarousel.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/UncontrolledCollapse.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/__tests__/utils.spec' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Alert' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Badge' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Breadcrumb' {
  declare module.exports: any;
}

declare module 'reactstrap/src/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Button' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ButtonGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ButtonToggle' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Card' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardBody' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardColumns' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardDeck' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardFooter' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardImg' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardImgOverlay' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardLink' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardSubtitle' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardText' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CardTitle' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Carousel' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CarouselCaption' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CarouselControl' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CarouselIndicators' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CarouselItem' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Col' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Collapse' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Container' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CustomFileInput' {
  declare module.exports: any;
}

declare module 'reactstrap/src/CustomInput' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Dropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/src/DropdownContext' {
  declare module.exports: any;
}

declare module 'reactstrap/src/DropdownItem' {
  declare module.exports: any;
}

declare module 'reactstrap/src/DropdownMenu' {
  declare module.exports: any;
}

declare module 'reactstrap/src/DropdownToggle' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Fade' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Form' {
  declare module.exports: any;
}

declare module 'reactstrap/src/FormFeedback' {
  declare module.exports: any;
}

declare module 'reactstrap/src/FormGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/src/FormText' {
  declare module.exports: any;
}

declare module 'reactstrap/src' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Input' {
  declare module.exports: any;
}

declare module 'reactstrap/src/InputGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/src/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'reactstrap/src/InputGroupButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/src/InputGroupText' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Jumbotron' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Label' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ListGroup' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ListGroupItem' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ListGroupItemHeading' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ListGroupItemText' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Media' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Modal' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ModalBody' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ModalFooter' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ModalHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Nav' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Navbar' {
  declare module.exports: any;
}

declare module 'reactstrap/src/NavbarBrand' {
  declare module.exports: any;
}

declare module 'reactstrap/src/NavbarText' {
  declare module.exports: any;
}

declare module 'reactstrap/src/NavbarToggler' {
  declare module.exports: any;
}

declare module 'reactstrap/src/NavItem' {
  declare module.exports: any;
}

declare module 'reactstrap/src/NavLink' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Pagination' {
  declare module.exports: any;
}

declare module 'reactstrap/src/PaginationItem' {
  declare module.exports: any;
}

declare module 'reactstrap/src/PaginationLink' {
  declare module.exports: any;
}

declare module 'reactstrap/src/polyfill' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Popover' {
  declare module.exports: any;
}

declare module 'reactstrap/src/PopoverBody' {
  declare module.exports: any;
}

declare module 'reactstrap/src/PopoverHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/src/PopperContent' {
  declare module.exports: any;
}

declare module 'reactstrap/src/PopperTargetHelper' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Portal' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Progress' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Row' {
  declare module.exports: any;
}

declare module 'reactstrap/src/setupTests' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Spinner' {
  declare module.exports: any;
}

declare module 'reactstrap/src/TabContent' {
  declare module.exports: any;
}

declare module 'reactstrap/src/TabContext' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Table' {
  declare module.exports: any;
}

declare module 'reactstrap/src/TabPane' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Toast' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ToastBody' {
  declare module.exports: any;
}

declare module 'reactstrap/src/ToastHeader' {
  declare module.exports: any;
}

declare module 'reactstrap/src/Tooltip' {
  declare module.exports: any;
}

declare module 'reactstrap/src/TooltipPopoverWrapper' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledAlert' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledButtonDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledCarousel' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledCollapse' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledDropdown' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledPopover' {
  declare module.exports: any;
}

declare module 'reactstrap/src/UncontrolledTooltip' {
  declare module.exports: any;
}

declare module 'reactstrap/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactstrap/dist/reactstrap.cjs.js' {
  declare module.exports: $Exports<'reactstrap/dist/reactstrap.cjs'>;
}
declare module 'reactstrap/dist/reactstrap.es.js' {
  declare module.exports: $Exports<'reactstrap/dist/reactstrap.es'>;
}
declare module 'reactstrap/dist/reactstrap.full.js' {
  declare module.exports: $Exports<'reactstrap/dist/reactstrap.full'>;
}
declare module 'reactstrap/dist/reactstrap.full.min.js' {
  declare module.exports: $Exports<'reactstrap/dist/reactstrap.full.min'>;
}
declare module 'reactstrap/dist/reactstrap.js' {
  declare module.exports: $Exports<'reactstrap/dist/reactstrap'>;
}
declare module 'reactstrap/dist/reactstrap.min.js' {
  declare module.exports: $Exports<'reactstrap/dist/reactstrap.min'>;
}
declare module 'reactstrap/es/Alert.js' {
  declare module.exports: $Exports<'reactstrap/es/Alert'>;
}
declare module 'reactstrap/es/Badge.js' {
  declare module.exports: $Exports<'reactstrap/es/Badge'>;
}
declare module 'reactstrap/es/Breadcrumb.js' {
  declare module.exports: $Exports<'reactstrap/es/Breadcrumb'>;
}
declare module 'reactstrap/es/BreadcrumbItem.js' {
  declare module.exports: $Exports<'reactstrap/es/BreadcrumbItem'>;
}
declare module 'reactstrap/es/Button.js' {
  declare module.exports: $Exports<'reactstrap/es/Button'>;
}
declare module 'reactstrap/es/ButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/es/ButtonDropdown'>;
}
declare module 'reactstrap/es/ButtonGroup.js' {
  declare module.exports: $Exports<'reactstrap/es/ButtonGroup'>;
}
declare module 'reactstrap/es/ButtonToggle.js' {
  declare module.exports: $Exports<'reactstrap/es/ButtonToggle'>;
}
declare module 'reactstrap/es/ButtonToolbar.js' {
  declare module.exports: $Exports<'reactstrap/es/ButtonToolbar'>;
}
declare module 'reactstrap/es/Card.js' {
  declare module.exports: $Exports<'reactstrap/es/Card'>;
}
declare module 'reactstrap/es/CardBody.js' {
  declare module.exports: $Exports<'reactstrap/es/CardBody'>;
}
declare module 'reactstrap/es/CardColumns.js' {
  declare module.exports: $Exports<'reactstrap/es/CardColumns'>;
}
declare module 'reactstrap/es/CardDeck.js' {
  declare module.exports: $Exports<'reactstrap/es/CardDeck'>;
}
declare module 'reactstrap/es/CardFooter.js' {
  declare module.exports: $Exports<'reactstrap/es/CardFooter'>;
}
declare module 'reactstrap/es/CardGroup.js' {
  declare module.exports: $Exports<'reactstrap/es/CardGroup'>;
}
declare module 'reactstrap/es/CardHeader.js' {
  declare module.exports: $Exports<'reactstrap/es/CardHeader'>;
}
declare module 'reactstrap/es/CardImg.js' {
  declare module.exports: $Exports<'reactstrap/es/CardImg'>;
}
declare module 'reactstrap/es/CardImgOverlay.js' {
  declare module.exports: $Exports<'reactstrap/es/CardImgOverlay'>;
}
declare module 'reactstrap/es/CardLink.js' {
  declare module.exports: $Exports<'reactstrap/es/CardLink'>;
}
declare module 'reactstrap/es/CardSubtitle.js' {
  declare module.exports: $Exports<'reactstrap/es/CardSubtitle'>;
}
declare module 'reactstrap/es/CardText.js' {
  declare module.exports: $Exports<'reactstrap/es/CardText'>;
}
declare module 'reactstrap/es/CardTitle.js' {
  declare module.exports: $Exports<'reactstrap/es/CardTitle'>;
}
declare module 'reactstrap/es/Carousel.js' {
  declare module.exports: $Exports<'reactstrap/es/Carousel'>;
}
declare module 'reactstrap/es/CarouselCaption.js' {
  declare module.exports: $Exports<'reactstrap/es/CarouselCaption'>;
}
declare module 'reactstrap/es/CarouselControl.js' {
  declare module.exports: $Exports<'reactstrap/es/CarouselControl'>;
}
declare module 'reactstrap/es/CarouselIndicators.js' {
  declare module.exports: $Exports<'reactstrap/es/CarouselIndicators'>;
}
declare module 'reactstrap/es/CarouselItem.js' {
  declare module.exports: $Exports<'reactstrap/es/CarouselItem'>;
}
declare module 'reactstrap/es/Col.js' {
  declare module.exports: $Exports<'reactstrap/es/Col'>;
}
declare module 'reactstrap/es/Collapse.js' {
  declare module.exports: $Exports<'reactstrap/es/Collapse'>;
}
declare module 'reactstrap/es/Container.js' {
  declare module.exports: $Exports<'reactstrap/es/Container'>;
}
declare module 'reactstrap/es/CustomFileInput.js' {
  declare module.exports: $Exports<'reactstrap/es/CustomFileInput'>;
}
declare module 'reactstrap/es/CustomInput.js' {
  declare module.exports: $Exports<'reactstrap/es/CustomInput'>;
}
declare module 'reactstrap/es/Dropdown.js' {
  declare module.exports: $Exports<'reactstrap/es/Dropdown'>;
}
declare module 'reactstrap/es/DropdownContext.js' {
  declare module.exports: $Exports<'reactstrap/es/DropdownContext'>;
}
declare module 'reactstrap/es/DropdownItem.js' {
  declare module.exports: $Exports<'reactstrap/es/DropdownItem'>;
}
declare module 'reactstrap/es/DropdownMenu.js' {
  declare module.exports: $Exports<'reactstrap/es/DropdownMenu'>;
}
declare module 'reactstrap/es/DropdownToggle.js' {
  declare module.exports: $Exports<'reactstrap/es/DropdownToggle'>;
}
declare module 'reactstrap/es/Fade.js' {
  declare module.exports: $Exports<'reactstrap/es/Fade'>;
}
declare module 'reactstrap/es/Form.js' {
  declare module.exports: $Exports<'reactstrap/es/Form'>;
}
declare module 'reactstrap/es/FormFeedback.js' {
  declare module.exports: $Exports<'reactstrap/es/FormFeedback'>;
}
declare module 'reactstrap/es/FormGroup.js' {
  declare module.exports: $Exports<'reactstrap/es/FormGroup'>;
}
declare module 'reactstrap/es/FormText.js' {
  declare module.exports: $Exports<'reactstrap/es/FormText'>;
}
declare module 'reactstrap/es/index' {
  declare module.exports: $Exports<'reactstrap/es'>;
}
declare module 'reactstrap/es/index.js' {
  declare module.exports: $Exports<'reactstrap/es'>;
}
declare module 'reactstrap/es/Input.js' {
  declare module.exports: $Exports<'reactstrap/es/Input'>;
}
declare module 'reactstrap/es/InputGroup.js' {
  declare module.exports: $Exports<'reactstrap/es/InputGroup'>;
}
declare module 'reactstrap/es/InputGroupAddon.js' {
  declare module.exports: $Exports<'reactstrap/es/InputGroupAddon'>;
}
declare module 'reactstrap/es/InputGroupButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/es/InputGroupButtonDropdown'>;
}
declare module 'reactstrap/es/InputGroupText.js' {
  declare module.exports: $Exports<'reactstrap/es/InputGroupText'>;
}
declare module 'reactstrap/es/Jumbotron.js' {
  declare module.exports: $Exports<'reactstrap/es/Jumbotron'>;
}
declare module 'reactstrap/es/Label.js' {
  declare module.exports: $Exports<'reactstrap/es/Label'>;
}
declare module 'reactstrap/es/ListGroup.js' {
  declare module.exports: $Exports<'reactstrap/es/ListGroup'>;
}
declare module 'reactstrap/es/ListGroupItem.js' {
  declare module.exports: $Exports<'reactstrap/es/ListGroupItem'>;
}
declare module 'reactstrap/es/ListGroupItemHeading.js' {
  declare module.exports: $Exports<'reactstrap/es/ListGroupItemHeading'>;
}
declare module 'reactstrap/es/ListGroupItemText.js' {
  declare module.exports: $Exports<'reactstrap/es/ListGroupItemText'>;
}
declare module 'reactstrap/es/Media.js' {
  declare module.exports: $Exports<'reactstrap/es/Media'>;
}
declare module 'reactstrap/es/Modal.js' {
  declare module.exports: $Exports<'reactstrap/es/Modal'>;
}
declare module 'reactstrap/es/ModalBody.js' {
  declare module.exports: $Exports<'reactstrap/es/ModalBody'>;
}
declare module 'reactstrap/es/ModalFooter.js' {
  declare module.exports: $Exports<'reactstrap/es/ModalFooter'>;
}
declare module 'reactstrap/es/ModalHeader.js' {
  declare module.exports: $Exports<'reactstrap/es/ModalHeader'>;
}
declare module 'reactstrap/es/Nav.js' {
  declare module.exports: $Exports<'reactstrap/es/Nav'>;
}
declare module 'reactstrap/es/Navbar.js' {
  declare module.exports: $Exports<'reactstrap/es/Navbar'>;
}
declare module 'reactstrap/es/NavbarBrand.js' {
  declare module.exports: $Exports<'reactstrap/es/NavbarBrand'>;
}
declare module 'reactstrap/es/NavbarText.js' {
  declare module.exports: $Exports<'reactstrap/es/NavbarText'>;
}
declare module 'reactstrap/es/NavbarToggler.js' {
  declare module.exports: $Exports<'reactstrap/es/NavbarToggler'>;
}
declare module 'reactstrap/es/NavItem.js' {
  declare module.exports: $Exports<'reactstrap/es/NavItem'>;
}
declare module 'reactstrap/es/NavLink.js' {
  declare module.exports: $Exports<'reactstrap/es/NavLink'>;
}
declare module 'reactstrap/es/Pagination.js' {
  declare module.exports: $Exports<'reactstrap/es/Pagination'>;
}
declare module 'reactstrap/es/PaginationItem.js' {
  declare module.exports: $Exports<'reactstrap/es/PaginationItem'>;
}
declare module 'reactstrap/es/PaginationLink.js' {
  declare module.exports: $Exports<'reactstrap/es/PaginationLink'>;
}
declare module 'reactstrap/es/polyfill.js' {
  declare module.exports: $Exports<'reactstrap/es/polyfill'>;
}
declare module 'reactstrap/es/Popover.js' {
  declare module.exports: $Exports<'reactstrap/es/Popover'>;
}
declare module 'reactstrap/es/PopoverBody.js' {
  declare module.exports: $Exports<'reactstrap/es/PopoverBody'>;
}
declare module 'reactstrap/es/PopoverHeader.js' {
  declare module.exports: $Exports<'reactstrap/es/PopoverHeader'>;
}
declare module 'reactstrap/es/PopperContent.js' {
  declare module.exports: $Exports<'reactstrap/es/PopperContent'>;
}
declare module 'reactstrap/es/PopperTargetHelper.js' {
  declare module.exports: $Exports<'reactstrap/es/PopperTargetHelper'>;
}
declare module 'reactstrap/es/Portal.js' {
  declare module.exports: $Exports<'reactstrap/es/Portal'>;
}
declare module 'reactstrap/es/Progress.js' {
  declare module.exports: $Exports<'reactstrap/es/Progress'>;
}
declare module 'reactstrap/es/Row.js' {
  declare module.exports: $Exports<'reactstrap/es/Row'>;
}
declare module 'reactstrap/es/setupTests.js' {
  declare module.exports: $Exports<'reactstrap/es/setupTests'>;
}
declare module 'reactstrap/es/Spinner.js' {
  declare module.exports: $Exports<'reactstrap/es/Spinner'>;
}
declare module 'reactstrap/es/TabContent.js' {
  declare module.exports: $Exports<'reactstrap/es/TabContent'>;
}
declare module 'reactstrap/es/TabContext.js' {
  declare module.exports: $Exports<'reactstrap/es/TabContext'>;
}
declare module 'reactstrap/es/Table.js' {
  declare module.exports: $Exports<'reactstrap/es/Table'>;
}
declare module 'reactstrap/es/TabPane.js' {
  declare module.exports: $Exports<'reactstrap/es/TabPane'>;
}
declare module 'reactstrap/es/Toast.js' {
  declare module.exports: $Exports<'reactstrap/es/Toast'>;
}
declare module 'reactstrap/es/ToastBody.js' {
  declare module.exports: $Exports<'reactstrap/es/ToastBody'>;
}
declare module 'reactstrap/es/ToastHeader.js' {
  declare module.exports: $Exports<'reactstrap/es/ToastHeader'>;
}
declare module 'reactstrap/es/Tooltip.js' {
  declare module.exports: $Exports<'reactstrap/es/Tooltip'>;
}
declare module 'reactstrap/es/TooltipPopoverWrapper.js' {
  declare module.exports: $Exports<'reactstrap/es/TooltipPopoverWrapper'>;
}
declare module 'reactstrap/es/UncontrolledAlert.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledAlert'>;
}
declare module 'reactstrap/es/UncontrolledButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledButtonDropdown'>;
}
declare module 'reactstrap/es/UncontrolledCarousel.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledCarousel'>;
}
declare module 'reactstrap/es/UncontrolledCollapse.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledCollapse'>;
}
declare module 'reactstrap/es/UncontrolledDropdown.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledDropdown'>;
}
declare module 'reactstrap/es/UncontrolledPopover.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledPopover'>;
}
declare module 'reactstrap/es/UncontrolledTooltip.js' {
  declare module.exports: $Exports<'reactstrap/es/UncontrolledTooltip'>;
}
declare module 'reactstrap/es/utils.js' {
  declare module.exports: $Exports<'reactstrap/es/utils'>;
}
declare module 'reactstrap/lib/Alert.js' {
  declare module.exports: $Exports<'reactstrap/lib/Alert'>;
}
declare module 'reactstrap/lib/Badge.js' {
  declare module.exports: $Exports<'reactstrap/lib/Badge'>;
}
declare module 'reactstrap/lib/Breadcrumb.js' {
  declare module.exports: $Exports<'reactstrap/lib/Breadcrumb'>;
}
declare module 'reactstrap/lib/BreadcrumbItem.js' {
  declare module.exports: $Exports<'reactstrap/lib/BreadcrumbItem'>;
}
declare module 'reactstrap/lib/Button.js' {
  declare module.exports: $Exports<'reactstrap/lib/Button'>;
}
declare module 'reactstrap/lib/ButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/lib/ButtonDropdown'>;
}
declare module 'reactstrap/lib/ButtonGroup.js' {
  declare module.exports: $Exports<'reactstrap/lib/ButtonGroup'>;
}
declare module 'reactstrap/lib/ButtonToggle.js' {
  declare module.exports: $Exports<'reactstrap/lib/ButtonToggle'>;
}
declare module 'reactstrap/lib/ButtonToolbar.js' {
  declare module.exports: $Exports<'reactstrap/lib/ButtonToolbar'>;
}
declare module 'reactstrap/lib/Card.js' {
  declare module.exports: $Exports<'reactstrap/lib/Card'>;
}
declare module 'reactstrap/lib/CardBody.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardBody'>;
}
declare module 'reactstrap/lib/CardColumns.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardColumns'>;
}
declare module 'reactstrap/lib/CardDeck.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardDeck'>;
}
declare module 'reactstrap/lib/CardFooter.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardFooter'>;
}
declare module 'reactstrap/lib/CardGroup.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardGroup'>;
}
declare module 'reactstrap/lib/CardHeader.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardHeader'>;
}
declare module 'reactstrap/lib/CardImg.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardImg'>;
}
declare module 'reactstrap/lib/CardImgOverlay.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardImgOverlay'>;
}
declare module 'reactstrap/lib/CardLink.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardLink'>;
}
declare module 'reactstrap/lib/CardSubtitle.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardSubtitle'>;
}
declare module 'reactstrap/lib/CardText.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardText'>;
}
declare module 'reactstrap/lib/CardTitle.js' {
  declare module.exports: $Exports<'reactstrap/lib/CardTitle'>;
}
declare module 'reactstrap/lib/Carousel.js' {
  declare module.exports: $Exports<'reactstrap/lib/Carousel'>;
}
declare module 'reactstrap/lib/CarouselCaption.js' {
  declare module.exports: $Exports<'reactstrap/lib/CarouselCaption'>;
}
declare module 'reactstrap/lib/CarouselControl.js' {
  declare module.exports: $Exports<'reactstrap/lib/CarouselControl'>;
}
declare module 'reactstrap/lib/CarouselIndicators.js' {
  declare module.exports: $Exports<'reactstrap/lib/CarouselIndicators'>;
}
declare module 'reactstrap/lib/CarouselItem.js' {
  declare module.exports: $Exports<'reactstrap/lib/CarouselItem'>;
}
declare module 'reactstrap/lib/Col.js' {
  declare module.exports: $Exports<'reactstrap/lib/Col'>;
}
declare module 'reactstrap/lib/Collapse.js' {
  declare module.exports: $Exports<'reactstrap/lib/Collapse'>;
}
declare module 'reactstrap/lib/Container.js' {
  declare module.exports: $Exports<'reactstrap/lib/Container'>;
}
declare module 'reactstrap/lib/CustomFileInput.js' {
  declare module.exports: $Exports<'reactstrap/lib/CustomFileInput'>;
}
declare module 'reactstrap/lib/CustomInput.js' {
  declare module.exports: $Exports<'reactstrap/lib/CustomInput'>;
}
declare module 'reactstrap/lib/Dropdown.js' {
  declare module.exports: $Exports<'reactstrap/lib/Dropdown'>;
}
declare module 'reactstrap/lib/DropdownContext.js' {
  declare module.exports: $Exports<'reactstrap/lib/DropdownContext'>;
}
declare module 'reactstrap/lib/DropdownItem.js' {
  declare module.exports: $Exports<'reactstrap/lib/DropdownItem'>;
}
declare module 'reactstrap/lib/DropdownMenu.js' {
  declare module.exports: $Exports<'reactstrap/lib/DropdownMenu'>;
}
declare module 'reactstrap/lib/DropdownToggle.js' {
  declare module.exports: $Exports<'reactstrap/lib/DropdownToggle'>;
}
declare module 'reactstrap/lib/Fade.js' {
  declare module.exports: $Exports<'reactstrap/lib/Fade'>;
}
declare module 'reactstrap/lib/Form.js' {
  declare module.exports: $Exports<'reactstrap/lib/Form'>;
}
declare module 'reactstrap/lib/FormFeedback.js' {
  declare module.exports: $Exports<'reactstrap/lib/FormFeedback'>;
}
declare module 'reactstrap/lib/FormGroup.js' {
  declare module.exports: $Exports<'reactstrap/lib/FormGroup'>;
}
declare module 'reactstrap/lib/FormText.js' {
  declare module.exports: $Exports<'reactstrap/lib/FormText'>;
}
declare module 'reactstrap/lib/index' {
  declare module.exports: $Exports<'reactstrap/lib'>;
}
declare module 'reactstrap/lib/index.js' {
  declare module.exports: $Exports<'reactstrap/lib'>;
}
declare module 'reactstrap/lib/Input.js' {
  declare module.exports: $Exports<'reactstrap/lib/Input'>;
}
declare module 'reactstrap/lib/InputGroup.js' {
  declare module.exports: $Exports<'reactstrap/lib/InputGroup'>;
}
declare module 'reactstrap/lib/InputGroupAddon.js' {
  declare module.exports: $Exports<'reactstrap/lib/InputGroupAddon'>;
}
declare module 'reactstrap/lib/InputGroupButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/lib/InputGroupButtonDropdown'>;
}
declare module 'reactstrap/lib/InputGroupText.js' {
  declare module.exports: $Exports<'reactstrap/lib/InputGroupText'>;
}
declare module 'reactstrap/lib/Jumbotron.js' {
  declare module.exports: $Exports<'reactstrap/lib/Jumbotron'>;
}
declare module 'reactstrap/lib/Label.js' {
  declare module.exports: $Exports<'reactstrap/lib/Label'>;
}
declare module 'reactstrap/lib/ListGroup.js' {
  declare module.exports: $Exports<'reactstrap/lib/ListGroup'>;
}
declare module 'reactstrap/lib/ListGroupItem.js' {
  declare module.exports: $Exports<'reactstrap/lib/ListGroupItem'>;
}
declare module 'reactstrap/lib/ListGroupItemHeading.js' {
  declare module.exports: $Exports<'reactstrap/lib/ListGroupItemHeading'>;
}
declare module 'reactstrap/lib/ListGroupItemText.js' {
  declare module.exports: $Exports<'reactstrap/lib/ListGroupItemText'>;
}
declare module 'reactstrap/lib/Media.js' {
  declare module.exports: $Exports<'reactstrap/lib/Media'>;
}
declare module 'reactstrap/lib/Modal.js' {
  declare module.exports: $Exports<'reactstrap/lib/Modal'>;
}
declare module 'reactstrap/lib/ModalBody.js' {
  declare module.exports: $Exports<'reactstrap/lib/ModalBody'>;
}
declare module 'reactstrap/lib/ModalFooter.js' {
  declare module.exports: $Exports<'reactstrap/lib/ModalFooter'>;
}
declare module 'reactstrap/lib/ModalHeader.js' {
  declare module.exports: $Exports<'reactstrap/lib/ModalHeader'>;
}
declare module 'reactstrap/lib/Nav.js' {
  declare module.exports: $Exports<'reactstrap/lib/Nav'>;
}
declare module 'reactstrap/lib/Navbar.js' {
  declare module.exports: $Exports<'reactstrap/lib/Navbar'>;
}
declare module 'reactstrap/lib/NavbarBrand.js' {
  declare module.exports: $Exports<'reactstrap/lib/NavbarBrand'>;
}
declare module 'reactstrap/lib/NavbarText.js' {
  declare module.exports: $Exports<'reactstrap/lib/NavbarText'>;
}
declare module 'reactstrap/lib/NavbarToggler.js' {
  declare module.exports: $Exports<'reactstrap/lib/NavbarToggler'>;
}
declare module 'reactstrap/lib/NavItem.js' {
  declare module.exports: $Exports<'reactstrap/lib/NavItem'>;
}
declare module 'reactstrap/lib/NavLink.js' {
  declare module.exports: $Exports<'reactstrap/lib/NavLink'>;
}
declare module 'reactstrap/lib/Pagination.js' {
  declare module.exports: $Exports<'reactstrap/lib/Pagination'>;
}
declare module 'reactstrap/lib/PaginationItem.js' {
  declare module.exports: $Exports<'reactstrap/lib/PaginationItem'>;
}
declare module 'reactstrap/lib/PaginationLink.js' {
  declare module.exports: $Exports<'reactstrap/lib/PaginationLink'>;
}
declare module 'reactstrap/lib/polyfill.js' {
  declare module.exports: $Exports<'reactstrap/lib/polyfill'>;
}
declare module 'reactstrap/lib/Popover.js' {
  declare module.exports: $Exports<'reactstrap/lib/Popover'>;
}
declare module 'reactstrap/lib/PopoverBody.js' {
  declare module.exports: $Exports<'reactstrap/lib/PopoverBody'>;
}
declare module 'reactstrap/lib/PopoverHeader.js' {
  declare module.exports: $Exports<'reactstrap/lib/PopoverHeader'>;
}
declare module 'reactstrap/lib/PopperContent.js' {
  declare module.exports: $Exports<'reactstrap/lib/PopperContent'>;
}
declare module 'reactstrap/lib/PopperTargetHelper.js' {
  declare module.exports: $Exports<'reactstrap/lib/PopperTargetHelper'>;
}
declare module 'reactstrap/lib/Portal.js' {
  declare module.exports: $Exports<'reactstrap/lib/Portal'>;
}
declare module 'reactstrap/lib/Progress.js' {
  declare module.exports: $Exports<'reactstrap/lib/Progress'>;
}
declare module 'reactstrap/lib/Row.js' {
  declare module.exports: $Exports<'reactstrap/lib/Row'>;
}
declare module 'reactstrap/lib/setupTests.js' {
  declare module.exports: $Exports<'reactstrap/lib/setupTests'>;
}
declare module 'reactstrap/lib/Spinner.js' {
  declare module.exports: $Exports<'reactstrap/lib/Spinner'>;
}
declare module 'reactstrap/lib/TabContent.js' {
  declare module.exports: $Exports<'reactstrap/lib/TabContent'>;
}
declare module 'reactstrap/lib/TabContext.js' {
  declare module.exports: $Exports<'reactstrap/lib/TabContext'>;
}
declare module 'reactstrap/lib/Table.js' {
  declare module.exports: $Exports<'reactstrap/lib/Table'>;
}
declare module 'reactstrap/lib/TabPane.js' {
  declare module.exports: $Exports<'reactstrap/lib/TabPane'>;
}
declare module 'reactstrap/lib/Toast.js' {
  declare module.exports: $Exports<'reactstrap/lib/Toast'>;
}
declare module 'reactstrap/lib/ToastBody.js' {
  declare module.exports: $Exports<'reactstrap/lib/ToastBody'>;
}
declare module 'reactstrap/lib/ToastHeader.js' {
  declare module.exports: $Exports<'reactstrap/lib/ToastHeader'>;
}
declare module 'reactstrap/lib/Tooltip.js' {
  declare module.exports: $Exports<'reactstrap/lib/Tooltip'>;
}
declare module 'reactstrap/lib/TooltipPopoverWrapper.js' {
  declare module.exports: $Exports<'reactstrap/lib/TooltipPopoverWrapper'>;
}
declare module 'reactstrap/lib/UncontrolledAlert.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledAlert'>;
}
declare module 'reactstrap/lib/UncontrolledButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledButtonDropdown'>;
}
declare module 'reactstrap/lib/UncontrolledCarousel.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledCarousel'>;
}
declare module 'reactstrap/lib/UncontrolledCollapse.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledCollapse'>;
}
declare module 'reactstrap/lib/UncontrolledDropdown.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledDropdown'>;
}
declare module 'reactstrap/lib/UncontrolledPopover.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledPopover'>;
}
declare module 'reactstrap/lib/UncontrolledTooltip.js' {
  declare module.exports: $Exports<'reactstrap/lib/UncontrolledTooltip'>;
}
declare module 'reactstrap/lib/utils.js' {
  declare module.exports: $Exports<'reactstrap/lib/utils'>;
}
declare module 'reactstrap/src/__tests__/Alert.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Alert.spec'>;
}
declare module 'reactstrap/src/__tests__/Badge.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Badge.spec'>;
}
declare module 'reactstrap/src/__tests__/Breadcrumb.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Breadcrumb.spec'>;
}
declare module 'reactstrap/src/__tests__/BreadcrumbList.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/BreadcrumbList.spec'>;
}
declare module 'reactstrap/src/__tests__/Button.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Button.spec'>;
}
declare module 'reactstrap/src/__tests__/ButtonDropdown.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ButtonDropdown.spec'>;
}
declare module 'reactstrap/src/__tests__/ButtonGroup.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ButtonGroup.spec'>;
}
declare module 'reactstrap/src/__tests__/ButtonToggle.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ButtonToggle.spec'>;
}
declare module 'reactstrap/src/__tests__/ButtonToolbar.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ButtonToolbar.spec'>;
}
declare module 'reactstrap/src/__tests__/Card.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Card.spec'>;
}
declare module 'reactstrap/src/__tests__/CardBody.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardBody.spec'>;
}
declare module 'reactstrap/src/__tests__/CardColumns.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardColumns.spec'>;
}
declare module 'reactstrap/src/__tests__/CardDeck.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardDeck.spec'>;
}
declare module 'reactstrap/src/__tests__/CardFooter.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardFooter.spec'>;
}
declare module 'reactstrap/src/__tests__/CardGroup.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardGroup.spec'>;
}
declare module 'reactstrap/src/__tests__/CardHeader.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardHeader.spec'>;
}
declare module 'reactstrap/src/__tests__/CardImg.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardImg.spec'>;
}
declare module 'reactstrap/src/__tests__/CardImgOverlay.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardImgOverlay.spec'>;
}
declare module 'reactstrap/src/__tests__/CardLink.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardLink.spec'>;
}
declare module 'reactstrap/src/__tests__/CardSubtitle.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardSubtitle.spec'>;
}
declare module 'reactstrap/src/__tests__/CardText.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardText.spec'>;
}
declare module 'reactstrap/src/__tests__/CardTitle.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CardTitle.spec'>;
}
declare module 'reactstrap/src/__tests__/Carousel.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Carousel.spec'>;
}
declare module 'reactstrap/src/__tests__/Col.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Col.spec'>;
}
declare module 'reactstrap/src/__tests__/Collapse.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Collapse.spec'>;
}
declare module 'reactstrap/src/__tests__/Container.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Container.spec'>;
}
declare module 'reactstrap/src/__tests__/CustomInput.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/CustomInput.spec'>;
}
declare module 'reactstrap/src/__tests__/Dropdown.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Dropdown.spec'>;
}
declare module 'reactstrap/src/__tests__/DropdownItem.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/DropdownItem.spec'>;
}
declare module 'reactstrap/src/__tests__/DropdownMenu.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/DropdownMenu.spec'>;
}
declare module 'reactstrap/src/__tests__/DropdownToggle.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/DropdownToggle.spec'>;
}
declare module 'reactstrap/src/__tests__/Fade.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Fade.spec'>;
}
declare module 'reactstrap/src/__tests__/Form.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Form.spec'>;
}
declare module 'reactstrap/src/__tests__/FormFeedback.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/FormFeedback.spec'>;
}
declare module 'reactstrap/src/__tests__/FormGroup.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/FormGroup.spec'>;
}
declare module 'reactstrap/src/__tests__/FormText.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/FormText.spec'>;
}
declare module 'reactstrap/src/__tests__/Input.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Input.spec'>;
}
declare module 'reactstrap/src/__tests__/InputGroup.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/InputGroup.spec'>;
}
declare module 'reactstrap/src/__tests__/InputGroupAddon.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/InputGroupAddon.spec'>;
}
declare module 'reactstrap/src/__tests__/InputGroupButtonDropdown.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/InputGroupButtonDropdown.spec'>;
}
declare module 'reactstrap/src/__tests__/InputGroupText.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/InputGroupText.spec'>;
}
declare module 'reactstrap/src/__tests__/Jumbotron.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Jumbotron.spec'>;
}
declare module 'reactstrap/src/__tests__/Label.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Label.spec'>;
}
declare module 'reactstrap/src/__tests__/ListGroup.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ListGroup.spec'>;
}
declare module 'reactstrap/src/__tests__/ListGroupItem.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ListGroupItem.spec'>;
}
declare module 'reactstrap/src/__tests__/ListGroupItemHeading.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ListGroupItemHeading.spec'>;
}
declare module 'reactstrap/src/__tests__/ListGroupItemText.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ListGroupItemText.spec'>;
}
declare module 'reactstrap/src/__tests__/Media.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Media.spec'>;
}
declare module 'reactstrap/src/__tests__/Modal.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Modal.spec'>;
}
declare module 'reactstrap/src/__tests__/ModalBody.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ModalBody.spec'>;
}
declare module 'reactstrap/src/__tests__/ModalFooter.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ModalFooter.spec'>;
}
declare module 'reactstrap/src/__tests__/ModalHeader.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ModalHeader.spec'>;
}
declare module 'reactstrap/src/__tests__/Nav.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Nav.spec'>;
}
declare module 'reactstrap/src/__tests__/Navbar.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Navbar.spec'>;
}
declare module 'reactstrap/src/__tests__/NavbarText.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/NavbarText.spec'>;
}
declare module 'reactstrap/src/__tests__/NavbarToggler.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/NavbarToggler.spec'>;
}
declare module 'reactstrap/src/__tests__/NavBrand.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/NavBrand.spec'>;
}
declare module 'reactstrap/src/__tests__/NavItem.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/NavItem.spec'>;
}
declare module 'reactstrap/src/__tests__/NavLink.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/NavLink.spec'>;
}
declare module 'reactstrap/src/__tests__/Pagination.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Pagination.spec'>;
}
declare module 'reactstrap/src/__tests__/PaginationItem.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/PaginationItem.spec'>;
}
declare module 'reactstrap/src/__tests__/PaginationLink.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/PaginationLink.spec'>;
}
declare module 'reactstrap/src/__tests__/Popover.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Popover.spec'>;
}
declare module 'reactstrap/src/__tests__/PopoverBody.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/PopoverBody.spec'>;
}
declare module 'reactstrap/src/__tests__/PopoverHeader.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/PopoverHeader.spec'>;
}
declare module 'reactstrap/src/__tests__/PopperContent.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/PopperContent.spec'>;
}
declare module 'reactstrap/src/__tests__/Progress.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Progress.spec'>;
}
declare module 'reactstrap/src/__tests__/Row.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Row.spec'>;
}
declare module 'reactstrap/src/__tests__/Spinner.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Spinner.spec'>;
}
declare module 'reactstrap/src/__tests__/Table.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Table.spec'>;
}
declare module 'reactstrap/src/__tests__/Tabs.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Tabs.spec'>;
}
declare module 'reactstrap/src/__tests__/Toast.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Toast.spec'>;
}
declare module 'reactstrap/src/__tests__/ToastBody.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ToastBody.spec'>;
}
declare module 'reactstrap/src/__tests__/ToastHeader.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/ToastHeader.spec'>;
}
declare module 'reactstrap/src/__tests__/Tooltip.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Tooltip.spec'>;
}
declare module 'reactstrap/src/__tests__/TooltipPopoverWrapper.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/TooltipPopoverWrapper.spec'>;
}
declare module 'reactstrap/src/__tests__/Uncontrolled.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/Uncontrolled.spec'>;
}
declare module 'reactstrap/src/__tests__/UncontrolledCarousel.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/UncontrolledCarousel.spec'>;
}
declare module 'reactstrap/src/__tests__/UncontrolledCollapse.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/UncontrolledCollapse.spec'>;
}
declare module 'reactstrap/src/__tests__/utils.spec.js' {
  declare module.exports: $Exports<'reactstrap/src/__tests__/utils.spec'>;
}
declare module 'reactstrap/src/Alert.js' {
  declare module.exports: $Exports<'reactstrap/src/Alert'>;
}
declare module 'reactstrap/src/Badge.js' {
  declare module.exports: $Exports<'reactstrap/src/Badge'>;
}
declare module 'reactstrap/src/Breadcrumb.js' {
  declare module.exports: $Exports<'reactstrap/src/Breadcrumb'>;
}
declare module 'reactstrap/src/BreadcrumbItem.js' {
  declare module.exports: $Exports<'reactstrap/src/BreadcrumbItem'>;
}
declare module 'reactstrap/src/Button.js' {
  declare module.exports: $Exports<'reactstrap/src/Button'>;
}
declare module 'reactstrap/src/ButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/src/ButtonDropdown'>;
}
declare module 'reactstrap/src/ButtonGroup.js' {
  declare module.exports: $Exports<'reactstrap/src/ButtonGroup'>;
}
declare module 'reactstrap/src/ButtonToggle.js' {
  declare module.exports: $Exports<'reactstrap/src/ButtonToggle'>;
}
declare module 'reactstrap/src/ButtonToolbar.js' {
  declare module.exports: $Exports<'reactstrap/src/ButtonToolbar'>;
}
declare module 'reactstrap/src/Card.js' {
  declare module.exports: $Exports<'reactstrap/src/Card'>;
}
declare module 'reactstrap/src/CardBody.js' {
  declare module.exports: $Exports<'reactstrap/src/CardBody'>;
}
declare module 'reactstrap/src/CardColumns.js' {
  declare module.exports: $Exports<'reactstrap/src/CardColumns'>;
}
declare module 'reactstrap/src/CardDeck.js' {
  declare module.exports: $Exports<'reactstrap/src/CardDeck'>;
}
declare module 'reactstrap/src/CardFooter.js' {
  declare module.exports: $Exports<'reactstrap/src/CardFooter'>;
}
declare module 'reactstrap/src/CardGroup.js' {
  declare module.exports: $Exports<'reactstrap/src/CardGroup'>;
}
declare module 'reactstrap/src/CardHeader.js' {
  declare module.exports: $Exports<'reactstrap/src/CardHeader'>;
}
declare module 'reactstrap/src/CardImg.js' {
  declare module.exports: $Exports<'reactstrap/src/CardImg'>;
}
declare module 'reactstrap/src/CardImgOverlay.js' {
  declare module.exports: $Exports<'reactstrap/src/CardImgOverlay'>;
}
declare module 'reactstrap/src/CardLink.js' {
  declare module.exports: $Exports<'reactstrap/src/CardLink'>;
}
declare module 'reactstrap/src/CardSubtitle.js' {
  declare module.exports: $Exports<'reactstrap/src/CardSubtitle'>;
}
declare module 'reactstrap/src/CardText.js' {
  declare module.exports: $Exports<'reactstrap/src/CardText'>;
}
declare module 'reactstrap/src/CardTitle.js' {
  declare module.exports: $Exports<'reactstrap/src/CardTitle'>;
}
declare module 'reactstrap/src/Carousel.js' {
  declare module.exports: $Exports<'reactstrap/src/Carousel'>;
}
declare module 'reactstrap/src/CarouselCaption.js' {
  declare module.exports: $Exports<'reactstrap/src/CarouselCaption'>;
}
declare module 'reactstrap/src/CarouselControl.js' {
  declare module.exports: $Exports<'reactstrap/src/CarouselControl'>;
}
declare module 'reactstrap/src/CarouselIndicators.js' {
  declare module.exports: $Exports<'reactstrap/src/CarouselIndicators'>;
}
declare module 'reactstrap/src/CarouselItem.js' {
  declare module.exports: $Exports<'reactstrap/src/CarouselItem'>;
}
declare module 'reactstrap/src/Col.js' {
  declare module.exports: $Exports<'reactstrap/src/Col'>;
}
declare module 'reactstrap/src/Collapse.js' {
  declare module.exports: $Exports<'reactstrap/src/Collapse'>;
}
declare module 'reactstrap/src/Container.js' {
  declare module.exports: $Exports<'reactstrap/src/Container'>;
}
declare module 'reactstrap/src/CustomFileInput.js' {
  declare module.exports: $Exports<'reactstrap/src/CustomFileInput'>;
}
declare module 'reactstrap/src/CustomInput.js' {
  declare module.exports: $Exports<'reactstrap/src/CustomInput'>;
}
declare module 'reactstrap/src/Dropdown.js' {
  declare module.exports: $Exports<'reactstrap/src/Dropdown'>;
}
declare module 'reactstrap/src/DropdownContext.js' {
  declare module.exports: $Exports<'reactstrap/src/DropdownContext'>;
}
declare module 'reactstrap/src/DropdownItem.js' {
  declare module.exports: $Exports<'reactstrap/src/DropdownItem'>;
}
declare module 'reactstrap/src/DropdownMenu.js' {
  declare module.exports: $Exports<'reactstrap/src/DropdownMenu'>;
}
declare module 'reactstrap/src/DropdownToggle.js' {
  declare module.exports: $Exports<'reactstrap/src/DropdownToggle'>;
}
declare module 'reactstrap/src/Fade.js' {
  declare module.exports: $Exports<'reactstrap/src/Fade'>;
}
declare module 'reactstrap/src/Form.js' {
  declare module.exports: $Exports<'reactstrap/src/Form'>;
}
declare module 'reactstrap/src/FormFeedback.js' {
  declare module.exports: $Exports<'reactstrap/src/FormFeedback'>;
}
declare module 'reactstrap/src/FormGroup.js' {
  declare module.exports: $Exports<'reactstrap/src/FormGroup'>;
}
declare module 'reactstrap/src/FormText.js' {
  declare module.exports: $Exports<'reactstrap/src/FormText'>;
}
declare module 'reactstrap/src/index' {
  declare module.exports: $Exports<'reactstrap/src'>;
}
declare module 'reactstrap/src/index.js' {
  declare module.exports: $Exports<'reactstrap/src'>;
}
declare module 'reactstrap/src/Input.js' {
  declare module.exports: $Exports<'reactstrap/src/Input'>;
}
declare module 'reactstrap/src/InputGroup.js' {
  declare module.exports: $Exports<'reactstrap/src/InputGroup'>;
}
declare module 'reactstrap/src/InputGroupAddon.js' {
  declare module.exports: $Exports<'reactstrap/src/InputGroupAddon'>;
}
declare module 'reactstrap/src/InputGroupButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/src/InputGroupButtonDropdown'>;
}
declare module 'reactstrap/src/InputGroupText.js' {
  declare module.exports: $Exports<'reactstrap/src/InputGroupText'>;
}
declare module 'reactstrap/src/Jumbotron.js' {
  declare module.exports: $Exports<'reactstrap/src/Jumbotron'>;
}
declare module 'reactstrap/src/Label.js' {
  declare module.exports: $Exports<'reactstrap/src/Label'>;
}
declare module 'reactstrap/src/ListGroup.js' {
  declare module.exports: $Exports<'reactstrap/src/ListGroup'>;
}
declare module 'reactstrap/src/ListGroupItem.js' {
  declare module.exports: $Exports<'reactstrap/src/ListGroupItem'>;
}
declare module 'reactstrap/src/ListGroupItemHeading.js' {
  declare module.exports: $Exports<'reactstrap/src/ListGroupItemHeading'>;
}
declare module 'reactstrap/src/ListGroupItemText.js' {
  declare module.exports: $Exports<'reactstrap/src/ListGroupItemText'>;
}
declare module 'reactstrap/src/Media.js' {
  declare module.exports: $Exports<'reactstrap/src/Media'>;
}
declare module 'reactstrap/src/Modal.js' {
  declare module.exports: $Exports<'reactstrap/src/Modal'>;
}
declare module 'reactstrap/src/ModalBody.js' {
  declare module.exports: $Exports<'reactstrap/src/ModalBody'>;
}
declare module 'reactstrap/src/ModalFooter.js' {
  declare module.exports: $Exports<'reactstrap/src/ModalFooter'>;
}
declare module 'reactstrap/src/ModalHeader.js' {
  declare module.exports: $Exports<'reactstrap/src/ModalHeader'>;
}
declare module 'reactstrap/src/Nav.js' {
  declare module.exports: $Exports<'reactstrap/src/Nav'>;
}
declare module 'reactstrap/src/Navbar.js' {
  declare module.exports: $Exports<'reactstrap/src/Navbar'>;
}
declare module 'reactstrap/src/NavbarBrand.js' {
  declare module.exports: $Exports<'reactstrap/src/NavbarBrand'>;
}
declare module 'reactstrap/src/NavbarText.js' {
  declare module.exports: $Exports<'reactstrap/src/NavbarText'>;
}
declare module 'reactstrap/src/NavbarToggler.js' {
  declare module.exports: $Exports<'reactstrap/src/NavbarToggler'>;
}
declare module 'reactstrap/src/NavItem.js' {
  declare module.exports: $Exports<'reactstrap/src/NavItem'>;
}
declare module 'reactstrap/src/NavLink.js' {
  declare module.exports: $Exports<'reactstrap/src/NavLink'>;
}
declare module 'reactstrap/src/Pagination.js' {
  declare module.exports: $Exports<'reactstrap/src/Pagination'>;
}
declare module 'reactstrap/src/PaginationItem.js' {
  declare module.exports: $Exports<'reactstrap/src/PaginationItem'>;
}
declare module 'reactstrap/src/PaginationLink.js' {
  declare module.exports: $Exports<'reactstrap/src/PaginationLink'>;
}
declare module 'reactstrap/src/polyfill.js' {
  declare module.exports: $Exports<'reactstrap/src/polyfill'>;
}
declare module 'reactstrap/src/Popover.js' {
  declare module.exports: $Exports<'reactstrap/src/Popover'>;
}
declare module 'reactstrap/src/PopoverBody.js' {
  declare module.exports: $Exports<'reactstrap/src/PopoverBody'>;
}
declare module 'reactstrap/src/PopoverHeader.js' {
  declare module.exports: $Exports<'reactstrap/src/PopoverHeader'>;
}
declare module 'reactstrap/src/PopperContent.js' {
  declare module.exports: $Exports<'reactstrap/src/PopperContent'>;
}
declare module 'reactstrap/src/PopperTargetHelper.js' {
  declare module.exports: $Exports<'reactstrap/src/PopperTargetHelper'>;
}
declare module 'reactstrap/src/Portal.js' {
  declare module.exports: $Exports<'reactstrap/src/Portal'>;
}
declare module 'reactstrap/src/Progress.js' {
  declare module.exports: $Exports<'reactstrap/src/Progress'>;
}
declare module 'reactstrap/src/Row.js' {
  declare module.exports: $Exports<'reactstrap/src/Row'>;
}
declare module 'reactstrap/src/setupTests.js' {
  declare module.exports: $Exports<'reactstrap/src/setupTests'>;
}
declare module 'reactstrap/src/Spinner.js' {
  declare module.exports: $Exports<'reactstrap/src/Spinner'>;
}
declare module 'reactstrap/src/TabContent.js' {
  declare module.exports: $Exports<'reactstrap/src/TabContent'>;
}
declare module 'reactstrap/src/TabContext.js' {
  declare module.exports: $Exports<'reactstrap/src/TabContext'>;
}
declare module 'reactstrap/src/Table.js' {
  declare module.exports: $Exports<'reactstrap/src/Table'>;
}
declare module 'reactstrap/src/TabPane.js' {
  declare module.exports: $Exports<'reactstrap/src/TabPane'>;
}
declare module 'reactstrap/src/Toast.js' {
  declare module.exports: $Exports<'reactstrap/src/Toast'>;
}
declare module 'reactstrap/src/ToastBody.js' {
  declare module.exports: $Exports<'reactstrap/src/ToastBody'>;
}
declare module 'reactstrap/src/ToastHeader.js' {
  declare module.exports: $Exports<'reactstrap/src/ToastHeader'>;
}
declare module 'reactstrap/src/Tooltip.js' {
  declare module.exports: $Exports<'reactstrap/src/Tooltip'>;
}
declare module 'reactstrap/src/TooltipPopoverWrapper.js' {
  declare module.exports: $Exports<'reactstrap/src/TooltipPopoverWrapper'>;
}
declare module 'reactstrap/src/UncontrolledAlert.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledAlert'>;
}
declare module 'reactstrap/src/UncontrolledButtonDropdown.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledButtonDropdown'>;
}
declare module 'reactstrap/src/UncontrolledCarousel.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledCarousel'>;
}
declare module 'reactstrap/src/UncontrolledCollapse.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledCollapse'>;
}
declare module 'reactstrap/src/UncontrolledDropdown.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledDropdown'>;
}
declare module 'reactstrap/src/UncontrolledPopover.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledPopover'>;
}
declare module 'reactstrap/src/UncontrolledTooltip.js' {
  declare module.exports: $Exports<'reactstrap/src/UncontrolledTooltip'>;
}
declare module 'reactstrap/src/utils.js' {
  declare module.exports: $Exports<'reactstrap/src/utils'>;
}
